@Schedule.Api_HostAddress = https://localhost:7085

###
# Усі семестри

GET {{Schedule.Api_HostAddress}}/api/semesters
Accept: application/json

###
# Усі спеціальності

GET {{Schedule.Api_HostAddress}}/api/specialties
Accept: application/json

###
# Усі групи

GET {{Schedule.Api_HostAddress}}/api/groups
Accept: application/json

###
# Усі дисципліни

GET {{Schedule.Api_HostAddress}}/api/disciplines
Accept: application/json

###
# Усі викладачі

GET {{Schedule.Api_HostAddress}}/api/teachers
Accept: application/json

###
# Усі аудиторії

GET {{Schedule.Api_HostAddress}}/api/classrooms
Accept: application/json

###
# Дисципліни груп

GET {{Schedule.Api_HostAddress}}/api/groupdisciplines
Accept: application/json

###
# Призначення викладачів

GET {{Schedule.Api_HostAddress}}/api/teachingassignments
Accept: application/json

###
# Семестрове навантаження викладачів

GET {{Schedule.Api_HostAddress}}/api/teachersemesterloads
Accept: application/json

###
# Навантаження викладачів за дисциплінами

GET {{Schedule.Api_HostAddress}}/api/teacherdisciplineloads
Accept: application/json

###
# Дані конструктора для групи ІПЗ-21

GET {{Schedule.Api_HostAddress}}/api/BaseScheduleBuilder/semester/1/group/1
Accept: application/json

###
# Дані конструктора для групи КН-21

GET {{Schedule.Api_HostAddress}}/api/BaseScheduleBuilder/semester/1/group/2
Accept: application/json

###
# Усі базові пари

GET {{Schedule.Api_HostAddress}}/api/baselessons
Accept: application/json

###
# Створити базову пару для ІПЗ-21
# Понеділок, перша пара, щотижня

POST {{Schedule.Api_HostAddress}}/api/baselessons
Content-Type: application/json

{
  "teachingAssignmentId": 1,
  "groupId": 1,
  "teacherId": 1,
  "disciplineId": 1,
  "classRoomId": 1,
  "semesterId": 1,
  "lessonPosition": 1,
  "weekDay": 1,
  "weekProperty": 0,
  "lessonType": 1
}

###
# Усі базові пари після створення

GET {{Schedule.Api_HostAddress}}/api/baselessons
Accept: application/json

###
# Усі реальні пари

GET {{Schedule.Api_HostAddress}}/api/reallessons
Accept: application/json